former_path: '/data/work/cyye/0-project/11-PODGen/PODGen/src/models/Alex'
former_file: 'epoch=315-step=230364.ckpt'
load_middle: ''
use_old_config: False

pre_models:
  - model_path: '/data/work/cyye/0-project/11-PODGen/PODGen/src/models/topo'
    model_file: 'model_topo.pth'
    target: 3  # TI
    threshold: 0.2
    alpha: 1.0
    model_name: 'topo model'
  
  - model_path: '/data/work/cyye/0-project/11-PODGen/PODGen/src/models/mag'
    model_file: 'model_mag.pth'
    target: 0  
    threshold: 0.7
    alpha: 1.0
    model_name: 'mag model'
  
  - model_path: '/data/work/cyye/0-project/11-PODGen/PODGen/src/models/metal'
    model_file: 'model_metal.pth'
    target: 0
    threshold: 0.3
    alpha: 1.0
    model_name: 'gap model'

generate_setting:
  deterministic: False
  seed: 4803
  num_worker: 20
  batch_size: 50
  seed_dataset: '/data/work/cyye/0-project/11-PODGen/PODGen/data/mp_20/train.csv'
  output_file: '/data/work/cyye/0-project/11-PODGen/PODGen/podgen/mc_gen/topo_TI_test/'  ###################
  print_step: 50
  graph_method: mindistance

  max_T: 10
  min_T: 1
  T_type: 'cos'
  annealing_num_T: 2 #10
  annealing_tole_step: 2 # 350
  conv_window_size: 2 # 200

  isothermal_step: 50
  sample_every_n_step: 10

  xyz_std: 0.01
  l_std: 0.01

  propose_strategy:
    - 0    # for generate a new crystal
    - 3    # for update A
    - 6    # for update X
    - 6    # for update L

ele_score:
  13: 0.5 # Al
  15: 0.5 # P
  16: 0.5 # S
  31: 0.5 # Ga
  32: 0.5 # Ge
  33: 0.5 # As
  34: 0.5 # Se
  49: 0.5 # In
  50: 0.5 # Sn
  51: 0.5 # Sb
  52: 0.5 # Te
  82: 0.5 # Pb
  83: 0.5 # Bi